#!/usr/bin/env bash
## Install your load balancer (https://haproxy.debian.net/)
sudo apt-get -y update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4
sudo apt-get install -y haproxy
### Add "ubuntu" user as owner
sudo chown -R ubuntu /etc/haproxy/
### Configure HAproxy so that it send traffic to web-01 and web-02 and distribute requests using a roundrobin algorithm
echo -e "\n# Configure frontend (http) listen all *:80 and solve with backend (my-servers)\
\nfrontend http\
\n\tbind *:80\
\n\tmode http\
\n\tdefault_backend my-servers\
\n\
\n# Configure all server availables for frontend (http)\
\nbackend my-servers\
\n\tbalance roundrobin\
\n\tserver 3713-web-01 54.167.116.64:80 check\
\n\tserver 3713-web-02 54.242.204.48:80 check" >> /etc/haproxy/haproxy.cfg
### Start service.
sudo service haproxy restart
