#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

filename="/etc/passwd"
while IFS=: read -r username password userid groupid comment homedir cmdshell
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $comment"
done < $filename
